config/routes.rb
# == Route Map
#
#                       Prefix Verb     URI Pattern                               Controller#Action
#             new_user_session GET      /users/sign_in(.:format)                  devise/sessions#new
#                 user_session POST     /users/sign_in(.:format)                  devise/sessions#create
#         destroy_user_session DELETE   /users/sign_out(.:format)                 devise/sessions#destroy
#                user_password POST     /users/password(.:format)                 devise/passwords#create
#            new_user_password GET      /users/password/new(.:format)             devise/passwords#new
#           edit_user_password GET      /users/password/edit(.:format)            devise/passwords#edit
#                              PATCH    /users/password(.:format)                 devise/passwords#update
#                              PUT      /users/password(.:format)                 devise/passwords#update
#     cancel_user_registration GET      /users/cancel(.:format)                   devise/registrations#cancel
#            user_registration POST     /users(.:format)                          devise/registrations#create
#        new_user_registration GET      /users/sign_up(.:format)                  devise/registrations#new
#       edit_user_registration GET      /users/edit(.:format)                     devise/registrations#edit
#                              PATCH    /users(.:format)                          devise/registrations#update
#                              PUT      /users(.:format)                          devise/registrations#update
#                              DELETE   /users(.:format)                          devise/registrations#destroy
#            user_confirmation POST     /users/confirmation(.:format)             devise/confirmations#create
#        new_user_confirmation GET      /users/confirmation/new(.:format)         devise/confirmations#new
#                              GET      /users/confirmation(.:format)             devise/confirmations#show
#         new_api_user_session GET      /api/v1/auth/sign_in(.:format)            devise_token_auth/sessions#new
#             api_user_session POST     /api/v1/auth/sign_in(.:format)            devise_token_auth/sessions#create
#     destroy_api_user_session DELETE   /api/v1/auth/sign_out(.:format)           devise_token_auth/sessions#destroy
#            api_user_password POST     /api/v1/auth/password(.:format)           devise_token_auth/passwords#create
#        new_api_user_password GET      /api/v1/auth/password/new(.:format)       devise_token_auth/passwords#new
#       edit_api_user_password GET      /api/v1/auth/password/edit(.:format)      devise_token_auth/passwords#edit
#                              PATCH    /api/v1/auth/password(.:format)           devise_token_auth/passwords#update
#                              PUT      /api/v1/auth/password(.:format)           devise_token_auth/passwords#update
# cancel_api_user_registration GET      /api/v1/auth/cancel(.:format)             devise_token_auth/registrations#cancel
#        api_user_registration POST     /api/v1/auth(.:format)                    devise_token_auth/registrations#create
#    new_api_user_registration GET      /api/v1/auth/sign_up(.:format)            devise_token_auth/registrations#new
#   edit_api_user_registration GET      /api/v1/auth/edit(.:format)               devise_token_auth/registrations#edit
#                              PATCH    /api/v1/auth(.:format)                    devise_token_auth/registrations#update
#                              PUT      /api/v1/auth(.:format)                    devise_token_auth/registrations#update
#                              DELETE   /api/v1/auth(.:format)                    devise_token_auth/registrations#destroy
#        api_user_confirmation POST     /api/v1/auth/confirmation(.:format)       devise_token_auth/confirmations#create
#    new_api_user_confirmation GET      /api/v1/auth/confirmation/new(.:format)   devise_token_auth/confirmations#new
#                              GET      /api/v1/auth/confirmation(.:format)       devise_token_auth/confirmations#show
#   api_v1_auth_validate_token GET      /api/v1/auth/validate_token(.:format)     devise_token_auth/token_validations#validate_token
#          api_v1_auth_failure GET      /api/v1/auth/failure(.:format)            devise_token_auth/omniauth_callbacks#omniauth_failure
#                              GET      /api/v1/auth/:provider/callback(.:format) devise_token_auth/omniauth_callbacks#omniauth_success
#                              GET|POST /omniauth/:provider/callback(.:format)    devise_token_auth/omniauth_callbacks#redirect_callbacks
#             omniauth_failure GET|POST /omniauth/failure(.:format)               devise_token_auth/omniauth_callbacks#omniauth_failure
#                              GET      /api/v1/auth/:provider(.:format)          redirect(301)
#

Rails.application.routes.draw do

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'activities', to: 'pages#activities'
  get 'apply', to: 'pages#apply'
  get 'membership_index', to: 'pages#membership_index'
  get 'business_card_own', to: 'pages#business_card_own'
  get 'business_card_friend', to: 'pages#business_card_friend'
  get 'business_card_own_edito', to: 'pages#business_card_own_edito'
  get 'message_record', to: 'pages#message_record'
  get 'ticket_inquiring', to: 'pages#ticket_inquiring'
  get 'voting_record', to: 'pages#voting_record'
  get 'contacts', to: 'pages#contacts'

  devise_for :users

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'

      resources :events, only: %i(index show) do
        get :agendas
      end

      post "checkins/:agenda_id", to: 'checkins#create'
    end
  end
  
  namespace :manage do
    get :dashboard, controller: :pages
    resources :beacons, only: %i(new index) do
      get    :edit,       constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/ }
      put    :activate,   constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/ }
      delete :deactivate, constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/ }
      put    '/',         constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/ }, action: :update
      get    '/',         constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/ }, action: :show
      post :register, on: :collection, action: :create
      get  :oauth2callback, on: :collection, to: 'pages#oauth2callback'


      resources :attachments, only: %i(index destroy),
                constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/, id: /beacons\/\d{1}!\w{32}\/attachments\/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/ }

      namespace :attachments, constraints: { beacon_id: /beacons\/\d{1}![a-zA-Z0-9]{32}/ } do
        resources :announcements, :indoor_levels, only: %i(new create)
      end
    end

    resources :places, :events, :indoor_levels, :agendas

    resources :checkins, only: :index

    scope 'agendas/:agenda_id' do
      resource :speaker
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/backend/_header.html.slim
header.site-header
  .container-fluid
    = link_to 'BeConnect', '#', class: 'site-logo'

    button#show-hide-sidebar-toggle.show-hide-sidebar
      span Toggle Menu
    button.hamburger.hamburger-htla
      span Toggle Menu

    .site-header-content
      .site-header-content-in
        .site-header-shown
          .dropdown.dropdown-typical
            a#dd-user-profile.dropdown-toggle data-target='#' href='#' data-toggle='dropdown' aria-haspopup='true' ara-expanded='false'
              span.fa.fa-user-circle
              span.lbl.hidden-xs-down &nbsp;User Profile

            .dropdown-menu.dropdown-menu-right aria-labelledby='dd-user-profile'
              = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
                span.fa.fa-sign-out
                | &ensp;Logout

            = link_to '/', class: 'btn btn-nav btn-rounded btn-inline btn-danger-outline' do
              span.fa.fa-home
              span &nbsp;Home

          / button.burger-right type='button'
          /   i.font-icon-menu-addl

        .mobile-menu-right-overlay
        .site-header-collapsed
          .site-header-collapsed-in

app/views/shared/backend/_sidebar.html.slim
nav.side-menu
  ul.side-menu-list
    li.grey
      = link_to manage_dashboard_path do
        i.fa.fa-th-large aria-hidden='true'
        span.lbl Dashboard
    
    li.green.with-sub
      span
        i.fa.fa-map-marker
        span.lbl 地點
      ul
        li
          = link_to manage_places_path do
            span.lbl 地點管理
        li
          = link_to new_manage_place_path do
            span.lbl 新增地點
    
    li.gold.with-sub
      span
        i.fa.fa-thumb-tack
        span.lbl 場地
      ul
        li
        = link_to manage_indoor_levels_path do
          span.lbl 場地管理
        li
          = link_to new_manage_indoor_level_path do
            span.lbl 新增場地
        
    
    li.purple.with-sub
      span
        i.fa.fa-calendar
        span.lbl 活動
      ul
        li
          = link_to manage_events_path do
            span.lbl 活動管理
        li
          = link_to new_manage_event_path do
            span.lbl 新增活動
            
    li.blue.with-sub
      span
        i.fa.fa-star
        span.lbl 議程
      ul
        li
          = link_to manage_agendas_path do
            span.lbl 議程管理
        li
          = link_to new_manage_agenda_path do
            span.lbl 新增議程   
    
    li.brown.with-sub
      span
        i.fa.fa-location-arrow
        span.lbl Beacons
      ul
        li
          = link_to manage_beacons_path do
            span.lbl Beacon 管理
        li
          = link_to new_manage_beacon_path do
            span.lbl 新增 Beacon

    li.red
      = link_to manage_checkins_path do
        i.fa.fa-ticket
        span.lbl 我的簽到